#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       command line, like:
#
#           ksh Gradle
#
#       Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX shell features:
#         * functions;
#         * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
#           «${var#prefix}», «${var%suffix}», and «$( cmd )»;
#         * compound commands having a testable exit status, especially «case»;
#         * various built-in commands including «command», «set», and «ulimit».
#
#   Important for patching:
#
#   (2) This script targets any POSIX shell, so it avoids extensions provided
#       by Bash, Ksh, etc; in particular arrays are avoided.
#
#       The "traditional" practice of packing multiple parameters into a
#       space-separated string is a well documented source of bugs and security
#       problems, so this is (mostly) avoided, by progressively accumulating
#       options in "$@", and eventually passing that to Java.
#
#       Where the inherited environment variables (DEFAULT_JVM_OPTS, JAVA_OPTS,
#       and GRADLE_OPTS) rely on word-splitting, this is performed explicitly;
#       see the in-line comments for details.
#
#       There are tweaks for specific operating systems such as AIX, CygWin,
#       Darwin, MinGW, and NonStop.
#
#   (3) This script is generated from the Groovy template
#       https://github.com/gradle/gradle/blob/HEAD/platforms/jvm/plugins-application/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
#       within the Gradle project.
#
#       You can find Gradle at https://github.com/gradle/gradle/.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
# Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25036)
APP_HOME=$( cd -P "${APP_HOME:-./}" > /dev/null && printf '%s\n' "$PWD" ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# Build the Gradle wrapper jar from sources when the binary is not present.
ensure_gradle_wrapper_jar () {
    wrapper_jar="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
    properties_file="$APP_HOME/gradle/wrapper/gradle-wrapper.properties"

    if [ -r "$wrapper_jar" ] ; then
        return
    fi

    if [ ! -f "$properties_file" ] ; then
        die "ERROR: gradle-wrapper.properties is required to assemble gradle-wrapper.jar."
    fi

    distribution_url=$( sed -n 's/^distributionUrl=//p' "$properties_file" | head -n 1 )
    distribution_url=$( printf '%s\n' "$distribution_url" | tr -d '\r' | sed 's#\\:#:#g' )

    if [ -z "$distribution_url" ] ; then
        die "ERROR: distributionUrl is missing in gradle-wrapper.properties."
    fi

    distribution_base=${distribution_url##*/}
    distribution_nozip=${distribution_base%.zip}
    version_fragment=${distribution_nozip#gradle-}
    case "$version_fragment" in
        *-bin) version=${version_fragment%-bin} ;;
        *-all) version=${version_fragment%-all} ;;
        *-src) version=${version_fragment%-src} ;;
        *)     version=$version_fragment ;;
    esac

    if command -v jar >/dev/null 2>&1 ; then
        jar_cmd=$( command -v jar )
    else
        jar_cmd=${JAVACMD%/java}/jar
    fi

    if [ ! -x "$jar_cmd" ] ; then
        die "ERROR: gradle-wrapper.jar is missing and the jar tool is not available."
    fi

    build_dir="$APP_HOME/gradle/wrapper/build"
    dist_zip="$build_dir/distribution.zip"
    shared_jar="$build_dir/gradle-wrapper-shared.jar"
    main_jar="$build_dir/gradle-wrapper-main.jar"
    cli_jar="$build_dir/gradle-cli.jar"
    base_services_jar="$build_dir/gradle-base-services.jar"
    files_jar="$build_dir/gradle-files.jar"
    extracted_dir="$build_dir/extracted"
    classes_dir="$build_dir/classes"
    manifest_file="$build_dir/MANIFEST.MF"
    shared_entry="gradle-$version/lib/gradle-wrapper-shared-$version.jar"
    main_entry="gradle-$version/lib/plugins/gradle-wrapper-main-$version.jar"
    cli_entry="gradle-$version/lib/gradle-cli-$version.jar"
    base_services_entry="gradle-$version/lib/gradle-base-services-$version.jar"
    files_entry="gradle-$version/lib/gradle-files-$version.jar"

    rm -rf "$build_dir"
    mkdir -p "$classes_dir" "$extracted_dir"

    if command -v curl >/dev/null 2>&1 ; then
        if ! curl -sSfL "$distribution_url" -o "$dist_zip" ; then
            die "ERROR: Failed to download Gradle distribution from $distribution_url"
        fi
    elif command -v wget >/dev/null 2>&1 ; then
        if ! wget -q "$distribution_url" -O "$dist_zip" ; then
            die "ERROR: Failed to download Gradle distribution from $distribution_url"
        fi
    else
        die "ERROR: Neither curl nor wget is available to download $distribution_url"
    fi

    extracted_shared=false
    extracted_main=false
    extracted_cli=false
    extracted_base_services=false
    extracted_files=false
    if command -v unzip >/dev/null 2>&1 ; then
        if unzip -p "$dist_zip" "$shared_entry" > "$shared_jar" ; then
            extracted_shared=true
        fi
        if unzip -p "$dist_zip" "$main_entry" > "$main_jar" ; then
            extracted_main=true
        fi
        if unzip -p "$dist_zip" "$cli_entry" > "$cli_jar" ; then
            extracted_cli=true
        fi
        if unzip -p "$dist_zip" "$base_services_entry" > "$base_services_jar" ; then
            extracted_base_services=true
        fi
        if unzip -p "$dist_zip" "$files_entry" > "$files_jar" ; then
            extracted_files=true
        fi
    fi

    if [ "$extracted_shared" != "true" ] || [ "$extracted_main" != "true" ] || [ "$extracted_cli" != "true" ] || [ "$extracted_base_services" != "true" ] || [ "$extracted_files" != "true" ] ; then
        rm -f "$shared_jar" "$main_jar" "$cli_jar" "$base_services_jar" "$files_jar"
        if ! ( cd "$extracted_dir" && "$jar_cmd" xf "$dist_zip" "$shared_entry" "$main_entry" "$cli_entry" "$base_services_entry" "$files_entry" ) ; then
            die "ERROR: Failed to extract Gradle wrapper components"
        fi
        if [ ! -f "$extracted_dir/$shared_entry" ] || [ ! -f "$extracted_dir/$main_entry" ] || [ ! -f "$extracted_dir/$cli_entry" ] || [ ! -f "$extracted_dir/$base_services_entry" ] || [ ! -f "$extracted_dir/$files_entry" ] ; then
            die "ERROR: Gradle wrapper components were not found in the distribution"
        fi
        if ! mv "$extracted_dir/$shared_entry" "$shared_jar" ; then
            die "ERROR: Failed to move shared wrapper jar"
        fi
        if ! mv "$extracted_dir/$main_entry" "$main_jar" ; then
            die "ERROR: Failed to move main wrapper jar"
        fi
        if ! mv "$extracted_dir/$cli_entry" "$cli_jar" ; then
            die "ERROR: Failed to move CLI wrapper jar"
        fi
        if ! mv "$extracted_dir/$base_services_entry" "$base_services_jar" ; then
            die "ERROR: Failed to move base services jar"
        fi
        if ! mv "$extracted_dir/$files_entry" "$files_jar" ; then
            die "ERROR: Failed to move files jar"
        fi
    fi

    if ! ( cd "$classes_dir" && "$jar_cmd" xf "$shared_jar" ); then
        die "ERROR: Failed to unpack gradle-wrapper-shared.jar"
    fi
    if ! ( cd "$classes_dir" && "$jar_cmd" xf "$main_jar" ); then
        die "ERROR: Failed to unpack gradle-wrapper-main.jar"
    fi
    if ! ( cd "$classes_dir" && "$jar_cmd" xf "$cli_jar" ); then
        die "ERROR: Failed to unpack gradle-cli.jar"
    fi
    if ! ( cd "$classes_dir" && "$jar_cmd" xf "$base_services_jar" ); then
        die "ERROR: Failed to unpack gradle-base-services.jar"
    fi
    if ! ( cd "$classes_dir" && "$jar_cmd" xf "$files_jar" ); then
        die "ERROR: Failed to unpack gradle-files.jar"
    fi

    printf 'Manifest-Version: 1.0\nMain-Class: org.gradle.wrapper.GradleWrapperMain\n' > "$manifest_file"

    if ! "$jar_cmd" cfm "$wrapper_jar" "$manifest_file" -C "$classes_dir" . ; then
        die "ERROR: Failed to assemble gradle-wrapper.jar"
    fi

    rm -rf "$build_dir"
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH="\\\"\\\""


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Ensure the wrapper jar exists before executing.
ensure_gradle_wrapper_jar

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC2039,SC3045
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC2039,SC3045
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # don't mess with options #(
              /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
                    [ -e "$t" ] ;;                      #(
              *)    false ;;
            esac
        then
            arg=$( cygpath --path --ignore --mixed "$arg" )
        fi
        # Roll the args list around exactly as many times as the number of
        # args, so each arg winds up back in the position where it started, but
        # possibly modified.
        #
        # NB: a `for` loop captures its iteration list before it begins, so
        # changing the positional parameters here affects neither the number of
        # iterations, nor the values presented in `arg`.
        shift                   # remove old arg
        set -- "$@" "$arg"      # push replacement arg
    done
fi


# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Collect all arguments for the java command:
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and optsEnvironmentVar are not allowed to contain shell fragments,
#     and any embedded shellness will be escaped.
#   * For example: A user cannot expect ${Hostname} to be expanded, as it is an environment variable and will be
#     treated as '${Hostname}' itself on the command line.

set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        -jar "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" \
        "$@"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
#
# With -n1 it outputs one arg per line, with the quotes and backslashes removed.
#
# In Bash we could simply go:
#
#   readarray ARGS < <( xargs -n1 <<<"$var" ) &&
#   set -- "${ARGS[@]}" "$@"
#
# but POSIX shell has neither arrays nor command substitution, so instead we
# post-process each arg (as a line of input to sed) to backslash-escape any
# character that might be a shell metacharacter, then use eval to reverse
# that process (while maintaining the separation between arguments), and wrap
# the whole thing up as a single "set" statement.
#
# This will of course break if any of these variables contains a newline or
# an unmatched quote.
#

eval "set -- $(
        printf '%s\n' "$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS" |
        xargs -n1 |
        sed ' s~[^-[:alnum:]+,./:=@_]~\\&~g; ' |
        tr '\n' ' '
    )" '"$@"'

exec "$JAVACMD" "$@"
