spring:
  application:
    name: bank-account-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always

esdb:
  server:
    uri: ${ESDB_SERVER_URI:http://localhost:3000}
    api-token: ${ESDB_API_TOKEN:secret}

opencqrs:
  command-handling:
    cache:
      type: in_memory
  event-handling:
    standard:
      life-cycle.partitions: 2
    groups:
      subscribing:
        sequence.resolution: no-sequence
      internalMoneyTransfer:
        life-cycle.partitions: 1
        life-cycle.controller: application-context
        progress.tracking: jdbc
      readModelProjection:
        progress.tracking: jdbc
  metadata:
    propagation:
      keys:
        - request-uri
