axon:
  axonserver:
    enabled: false
  eventhandling:
    processors:
      subscribing:
        mode: subscribing
      internalMoneyTransfer:
        mode: tracking
        thread-count: 1
        initial-segment-count: 1
      readModelProjection:
        mode: tracking
        thread-count: 1
        initial-segment-count: 1
  serializer:
    general: jackson
    events: jackson
    messages: jackson

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: secret
  sql:
    init:
      mode: always
