CREATE TABLE IF NOT EXISTS EVENTHANDLER_PROGRESS
(
    GROUP_KEY    VARCHAR(255) NOT NULL,
    PARTITION_ID BIGINT       NOT NULL,
    EVENT_ID     VARCHAR(255) NOT NULL,
    PRIMARY KEY (GROUP_KEY, PARTITION_ID)
);

CREATE TABLE IF NOT EXISTS bank_account_projection
(
    id BIGSERIAL NOT NULL,
    bank_account_id VARCHAR(255) NOT NULL,
    owner_name      TEXT         NOT NULL,
    balance FLOAT NOT NULL,
    transactions    JSONB        NOT NULL,
    PRIMARY KEY (id)
);
