< {%
    request.variables.set("bankAccountId", "002")
%}
POST http://localhost:8080/bankaccounts
Content-Type: application/json

{
  "bankAccountId": "{{bankAccountId}}",
  "ownerName": "Ted Tester"
}
