< {%
    request.variables.set("destinationBankAccountId", "")
    request.variables.set("originBankAccountId", "")
%}
POST http://localhost:8080/transfers
Content-Type: application/json

{
  "originBankAccountId": "{{originBankAccountId}}",
  "destinationBankAccountId": "{{destinationBankAccountId}}",
  "amount": 100.0,
  "reason": "some reason"
}
