< {%
    request.variables.set("destinationBankAccountId", "002")
    request.variables.set("originBankAccountId", "001")
%}
POST http://localhost:8080/transfers
Content-Type: application/json

{
  "originBankAccountId": "{{originBankAccountId}}",
  "destinationBankAccountId": "{{destinationBankAccountId}}",
  "amount": 500.0,
  "reason": "einfach so"
}
